import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "./../styles/Index.module.scss";
import Link from "next/link";
import Gallery from "@/src/components/gallery/Gallery";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Welcome</h1>
        <Link className={styles.link} href="/users">
          People
        </Link>

        <Gallery />
      </main>
    </>
  );
}
